version: '3'

services:
  tubesync:
    build: .
    container_name: tubesync
    entrypoint: 
      - "/bin/sh"
      - -ecx
      - |
          cd /app
          /usr/bin/python3 /app/manage.py test --verbosity=2
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=tubesync
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=tubesync